apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoangvm-rice-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rice-store
  template:
    metadata:
      labels:
        app: rice-store
    spec:
      containers:
      - name: rice-app
        image: 164693826317.dkr.ecr.ap-southeast-1.amazonaws.com/hoangvm-rice-app:latest
        env:
        - name: DB_HOST
          value: "terraform-20260121090946559500000001.cb8me0sq0urz.ap-southeast-1.rds.amazonaws.com"
        - name: DB_USER
          value: "admin_hoangvm"
        - name: DB_NAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "Hoangvm2026"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hoangvm-rice-service
spec:
  type: LoadBalancer 
  selector:
    app: rice-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

        