apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoangvm-rice-app
spec:
  replicas: 2 # Chạy 2 bản sao để web luôn sống
  selector:
    matchLabels:
      app: rice-store
  template:
    metadata:
      labels:
        app: rice-store
    spec:
      containers:
      - name: rice-app
        image: 164693826317.dkr.ecr.ap-southeast-1.amazonaws.com/hoangvm-rice-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hoangvm-rice-service
spec:
  type: LoadBalancer # Tạo địa chỉ web công khai
  selector:
    app: rice-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000