apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoangvm-ingress
  annotations:
    # Những dòng này để báo cho AWS Controller tạo ALB
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb # Khai báo sử dụng controller đã cài ở bước 1
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hoangvm-rice-service # Phải đúng tên Service ở trên
                port:
                  number: 80